# Read active ngrok tunnels from local inspector and write env snippets for E2M.
# Prerequisites: .\scripts\start-ngrok.ps1 already running; tunnels for :5173 and :3000 up.

$ErrorActionPreference = "Stop"

try {
  $tunnels = Invoke-RestMethod -Uri "http://127.0.0.1:4040/api/tunnels" -TimeoutSec 5
} catch {
  Write-Error "Cannot reach ngrok inspector at http://127.0.0.1:4040. Start tunnels first: .\scripts\start-ngrok.ps1"
}

$https = @($tunnels.tunnels | Where-Object { $_.public_url -like "https://*" })
if ($https.Count -lt 2) {
  Write-Error "Expected at least 2 HTTPS tunnels (frontend + API). Found $($https.Count)."
}

$fe = $https | Where-Object { $_.config.addr -match "5173" } | Select-Object -First 1
$api = $https | Where-Object { $_.config.addr -match "3000" } | Select-Object -First 1

if (-not $fe) { $fe = $https[0] }
if (-not $api) { $api = $https | Where-Object { $_.public_url -ne $fe.public_url } | Select-Object -First 1 }

$feUrl = $fe.public_url.TrimEnd("/")
$apiUrl = $api.public_url.TrimEnd("/")

Write-Host "Frontend tunnel: $feUrl"
Write-Host "API tunnel:      $apiUrl"

$root = Split-Path $PSScriptRoot -Parent
$snippet = @"
# Generated by scripts/apply-ngrok-env.ps1 — do not commit
# Backend (merge into backend/.env and/or root .env)
CORS_ORIGIN=$feUrl
FRONTEND_URL=$feUrl
API_PUBLIC_URL=$apiUrl

# Frontend (merge into frontend/.env)
VITE_API_URL=$apiUrl/api/v1
"@

$outPath = Join-Path $root ".env.ngrok"
Set-Content -Path $outPath -Value $snippet -Encoding UTF8
Write-Host ""
Write-Host "Wrote $outPath"
Write-Host "Copy those values into backend/.env and frontend/.env, then restart Nest + Vite."
Write-Host "Open the app at: $feUrl"
