# Read the active ngrok HTTPS URL and write env snippets for single-tunnel mode.
# Prerequisites: .\scripts\start-ngrok.ps1 running (tunnel -> :5173)

$ErrorActionPreference = "Stop"

function Set-EnvValue([string]$filePath, [string]$key, [string]$value) {
  if (-not (Test-Path $filePath)) {
    Set-Content -Path $filePath -Value "$key=$value" -Encoding UTF8
    return
  }
  $lines = Get-Content $filePath
  $found = $false
  $next = foreach ($line in $lines) {
    if ($line -match "^\s*$key\s*=") {
      $found = $true
      "$key=$value"
    } else {
      $line
    }
  }
  if (-not $found) { $next = @($next) + "$key=$value" }
  Set-Content -Path $filePath -Value $next -Encoding UTF8
}

try {
  $tunnels = Invoke-RestMethod -Uri "http://127.0.0.1:4040/api/tunnels" -TimeoutSec 5
} catch {
  Write-Error "Cannot reach ngrok inspector at http://127.0.0.1:4040. Start tunnels first: .\scripts\start-ngrok.ps1"
}

$https = @($tunnels.tunnels | Where-Object { $_.public_url -like "https://*" })
if ($https.Count -lt 1) {
  Write-Error "No HTTPS tunnels found. Start: .\scripts\start-ngrok.ps1"
}

$fe = $https | Where-Object { $_.config.addr -match "5173" } | Select-Object -First 1
if (-not $fe) { $fe = $https[0] }

$publicUrl = $fe.public_url.TrimEnd("/")
$addr = $fe.config.addr

Write-Host "Public URL: $publicUrl"
Write-Host "Forwarding:  $addr"

if ($addr -notmatch "5173") {
  Write-Host ""
  Write-Host "WARNING: Tunnel is not pointing at :5173 (got $addr)."
  Write-Host "Stop ngrok (Ctrl-C) and run .\scripts\start-ngrok.ps1 so it forwards to the Vite app."
}

$root = Split-Path $PSScriptRoot -Parent
$snippet = @"
# Generated by scripts/apply-ngrok-env.ps1 — do not commit
# Single-tunnel mode: ngrok -> Vite :5173, Vite proxies /api -> Nest :3000

# Backend (merge into backend/.env and/or root .env)
CORS_ORIGIN=$publicUrl
FRONTEND_URL=$publicUrl
API_PUBLIC_URL=$publicUrl

# Frontend (merge into frontend/.env) — same-origin via Vite proxy
VITE_API_URL=/api/v1
"@

$outPath = Join-Path $root ".env.ngrok"
Set-Content -Path $outPath -Value $snippet -Encoding UTF8

$backendEnv = Join-Path $root "backend\.env"
$frontendEnv = Join-Path $root "frontend\.env"
$rootEnv = Join-Path $root ".env"

Set-EnvValue $backendEnv "CORS_ORIGIN" $publicUrl
Set-EnvValue $backendEnv "FRONTEND_URL" $publicUrl
Set-EnvValue $backendEnv "API_PUBLIC_URL" $publicUrl
if (Test-Path $rootEnv) {
  Set-EnvValue $rootEnv "CORS_ORIGIN" $publicUrl
  Set-EnvValue $rootEnv "FRONTEND_URL" $publicUrl
  Set-EnvValue $rootEnv "API_PUBLIC_URL" $publicUrl
}
Set-EnvValue $frontendEnv "VITE_API_URL" "/api/v1"

Write-Host ""
Write-Host "Wrote $outPath"
Write-Host "Updated backend/.env + frontend/.env (and root .env if present)."
Write-Host "Restart Nest and Vite, then open: $publicUrl"
